#TIPOS DE LOOPS EM PYTHON

#LOOP FOR 

# Usando um loop for para iterar sobre uma lista

frutas = ["maçã", "banana", "laranja"]

for fruta in frutas:
    print(fruta)


#LOOP WHILE

# Usando um loop while para repetir até uma condição ser falsa
contador = 0

# while contador < 3:
#     print("Contagem:", contador)
#     contador += 1

#LOOP WHILE DIGITE 1 

sair = 0

while sair != 1:
    sair = int(input("Digite 1 para sair: "))
print("Você saiu!")


